/*
 * This source file was generated by the Gradle 'init' task
 */
package it.ktech.training;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appExists() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should exist");
    }
}
