/*
 * This source file was generated by the Gradle 'init' task
 */
package it.ktech.training;

public class App {
    public static void main(String[] args) {
        Terminal.printCentered("Gomoko");
        Terminal.printCentered("Creative Computing  Morristown, New Jersey");
        Terminal.println("\n\n");
        Terminal.println("""
                Welcome to the oriental game of Gomoko.

                The game is played on an N by N grid of a size
                that you specify. During your play, you may cover one grid
                intersection with a marker. The object of the game is to get
                5 adjacent markers in a row -- horizontally, vertically or
                diagonally. On the board diagram, your moves are marked
                with a '1' and the computer moves with a '2'.

                The computer does not keep track of who has won.
                To end the game, type -1,-1 for your move.
                """);

        while (true) {
            var game = new Gomoku();
            Terminal.println("We alternate moves.  You go first...");
            game.play();

            // NOTE: despite the prompt, the BASIC program doesn't check for
            // valid input - anything but 1 will halt the game
            if (!Terminal.scan("Play again (1 for yes, 0 for no)").equals("1")) {
                break;
            }
        }

        System.exit(0);
    }
}
