/*
 * This source file was generated by the Gradle 'init' task
 */
package it.ktech.training;

import java.util.Random;
import java.util.Scanner;

public class App {
    private static final Scanner scanner = new Scanner(System.in);
    private static final Random random = new Random();

    static void main(String[] args) {
        System.out.println("Provide a board size (7-19): ");
        int boardSize = scanner.nextInt();
        int[][] board = new int[boardSize][boardSize];
        while (true) {
            printBoard(board);
            System.out.println("YOUR PLAY (I, J): ");
            int inputX = scanner.nextInt();
            int inputY = scanner.nextInt();

            if (inputX == -1 && inputY == -1) break;

            int cordX = inputX - 1;
            int cordY = inputY - 1;

            if (!isValid(cordX, cordY, boardSize)){
                System.out.println("Illegal move");
                continue;
            } else if (isOccupied(cordX, cordY, board)){
                System.out.println("Already occupied");
                continue;
            }

            board[cordX][cordY] = 1;
            computerMove(cordX, cordY, board);

        }
        System.out.println("End of the game");
    }
    private static void printBoard(int[][] boardArray){
        for (int[] ints : boardArray) {
            for (int anInt : ints) {
                System.out.print(anInt + " ");
            }
            System.out.println();
        }
    }

    private static boolean isValid(int x, int y, int boardSize){
        return x >= 0 && x < boardSize && y >= 0 && y < boardSize;
    }
    private static boolean isOccupied(int x, int y, int[][] board){
        return board[x][y] != 0;
    }

    private static void computerMove(int x, int y, int[][] board){
        int boardSize = board.length;
        for (int i = -1; i <= 1; i++){
            for (int j = -1; j <= 1; j++){
                if (i == 0 && j == 0) continue;
                int checkRow = x + i;
                int checkCol = y + j;
                if (isValid(checkRow, checkCol, boardSize) && board[checkRow][checkCol] == 1){
                    int oppRow = x - i;
                    int oppCol = y - j;
                    if (isValid(oppRow, oppCol, boardSize) && board[oppRow][oppCol] == 0){
                        board[oppRow][oppCol] = 2;
                        return;
                    }
                }
            }
        }
        int row, col;
        do {
            row = random.nextInt(boardSize);
            col = random.nextInt(boardSize);
        } while (board[row][col] != 0);
        board[row][col] = 2;
    }
}
